language: c
os: linux
dist: bionic
services:
  - docker

# Don't build the pyup- or depandabot branches that pyup.io / dependabot creates; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^pyup-/
    - /^dependabot/

cache:
  directories:
    - $HOME/docker

env:
  global:
    # QUAY_USERNAME and QUAY_PASSWORD for docker image upload
    - secure: "lKaTzEL6UNiEfp+BWLOUILG9BMtjwEMpwt6Yag0cQGHix7qJ/ElZ0t3oFw6ZwuDmA5qceAXIdxHLUK9HGVI2MloLk8czGhjvtfJ4XhOxtEJRQ0VkDGPsKN4cfhB4ZjGo6GAPtNqStMyNiY7BZuTrZa7coDLCoUeYcOmTpi6pmd1rrkk725B9QCTuhFHbPhkuL2yu/Jk6WxkHJBKjmuZek+iQa7lRItgMrG0/319PXLvwIGGl00nLFy+Ly5Ciwzux4wuHLTySZQKu0H9FX81A7smM0FW/42kg3ckGa2qLxRw/Pi8Nm/aIk8LD0QXzI5N7HhFfidOTgDS8Mt1HgfxmTk4wUXZ/KvCCshqjimzMc/s9i9wPZX9UqqcfrpZkmwz8dzhm1bndN45ZOCy6xAYT6dzf8T4mLMDjVWSW4+DUoW4sYHRLVujjcMk7ybcwGV43VruPTJnc8XVAhT+VIMQkoPjhQmTOn8h82LRNGYtLa5RReCh9OPKVYB2Quz18FXMWgFt7A6VWudL0c7/8CusLvuo+pLcxt9pnV40rvu1YEohpEj8qR/qTSaDUBZM0J9SVf5zrZR80pZUnXkDF8nm+mcLOTley3YWipU19lCR7dzVyCAiQdVAuNPdnyem3Yk8enGkAJbfLd6eaIDs+p73D0JXh1Nx1px1movVLQH3ohIw="
    - secure: "w1614pomHLltkBhqWM2bOvbymFWIWKqSqqIBDvaNn9tbQScioItJoELBT7g7+cD7nyU7OvpQ1U2fk0xVkCeNvYU0xS1vP4o/VnZRpup7f7Tkiq+2rf4fjwYr3HHnJjwak1l9bsw6FkgzKaVvSdiUJHMVxiIuLd3fVozR7qjBBhTDxSlWGOpSgd+ttpgMZwU5zQjdaVQr1D7E8M0979ZnWMrNRyLiAUeHaPILS815b+ijgqR+i5nmu0/FTCGM9Ik4KIzIfWq8AdfPdbRiq8c+LrrTPfyKcIQJaHmfduYRM4LycGWwzkXFBNtLrJ7uFLG9RDVemOHuHOWIJX8qCUIV4XuESXxH3fUQr6r+yxquTJbzXxNtoaLa6tBOTQWKDrRjT4z9Mf9Im14F2V59EUDoQowHx5bjunOH5wg3ruYNKYYBFRYra5kx0CkKrqFBzyl8fTUEQLyx1HWTVUC1WTXEeD/aFKOSIxW5DxZr5W4LLlW2+Raa52ZzY28Q6AdueFQCRzoJ70/GsJRlSsBdWNOHN4gSp1cZuToLWY15y64QhAMVDpikB+V4hmkbceLiTqeWzTStNL1sa32RHr6i/9zeFZw1pMD1+eOg9x6fgODfh2sqr/zPbu2oONsHnc4D2jwsEax4o+Dv5QHLvK7jdyWUmu47a9QReoexXK60jZXs3CA="

# use YAML aliases and anchors to avoid duplication in stages
# c.f. https://github.com/travis-ci/travis-ci/issues/8295#issuecomment-454457787
_manylinux-build: &manylinux-build
      stage: "Build manylinux images"
      before_install:
        - travis-ci/load_cached_images.sh combined
      script:
        - PLATFORM=$PLATFORM TRAVIS_COMMIT=$TRAVIS_COMMIT ./build.sh glibc_skip
      deploy:
        provider: script
        script: docker/deploy.sh
        on:
          branch: master
          repo: pypa/manylinux

jobs:
  include:
    - stage: "Build patched i686 glibc for x86_64 image"
      env:
        - PLATFORM="x86_64"
      before_install:
        - travis-ci/load_cached_images.sh 32
      script:
        - PLATFORM=$PLATFORM docker/glibc/build.sh 32
      before_cache:
        - travis-ci/cache_images.sh 32
    - stage: "Build patched x86_64 glibc for x86_64 image"
      env:
        - PLATFORM="x86_64"
      before_install:
        - travis-ci/load_cached_images.sh 64
      script:
        - PLATFORM=$PLATFORM docker/glibc/build.sh 64
      before_cache:
        - travis-ci/cache_images.sh 64
    - stage: "Add patched glibcs to x86_64 image"
      env:
        - PLATFORM="x86_64"
      before_install:
        - travis-ci/load_cached_images.sh all
      script:
        - PLATFORM=$PLATFORM docker/glibc/build.sh all
      before_cache:
        - travis-ci/cache_images.sh combined_build
    - <<: *manylinux-build
      env:
        - PLATFORM="x86_64"
    - <<: *manylinux-build
      env:
        - PLATFORM="i686"
