language: c
os: linux
dist: focal
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
    packages:
    - docker-ce docker-ce-cli containerd.io docker-buildx-plugin
services:
  - docker

# Don't build the update-dependencies-pr branch; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^update-dependencies-pr/

cache:
  directories:
    - ${HOME}/buildx-cache/

env:
  global:
    # QUAY_USERNAME and QUAY_PASSWORD for docker image upload
    - secure: "lKaTzEL6UNiEfp+BWLOUILG9BMtjwEMpwt6Yag0cQGHix7qJ/ElZ0t3oFw6ZwuDmA5qceAXIdxHLUK9HGVI2MloLk8czGhjvtfJ4XhOxtEJRQ0VkDGPsKN4cfhB4ZjGo6GAPtNqStMyNiY7BZuTrZa7coDLCoUeYcOmTpi6pmd1rrkk725B9QCTuhFHbPhkuL2yu/Jk6WxkHJBKjmuZek+iQa7lRItgMrG0/319PXLvwIGGl00nLFy+Ly5Ciwzux4wuHLTySZQKu0H9FX81A7smM0FW/42kg3ckGa2qLxRw/Pi8Nm/aIk8LD0QXzI5N7HhFfidOTgDS8Mt1HgfxmTk4wUXZ/KvCCshqjimzMc/s9i9wPZX9UqqcfrpZkmwz8dzhm1bndN45ZOCy6xAYT6dzf8T4mLMDjVWSW4+DUoW4sYHRLVujjcMk7ybcwGV43VruPTJnc8XVAhT+VIMQkoPjhQmTOn8h82LRNGYtLa5RReCh9OPKVYB2Quz18FXMWgFt7A6VWudL0c7/8CusLvuo+pLcxt9pnV40rvu1YEohpEj8qR/qTSaDUBZM0J9SVf5zrZR80pZUnXkDF8nm+mcLOTley3YWipU19lCR7dzVyCAiQdVAuNPdnyem3Yk8enGkAJbfLd6eaIDs+p73D0JXh1Nx1px1movVLQH3ohIw="
    - secure: "w1614pomHLltkBhqWM2bOvbymFWIWKqSqqIBDvaNn9tbQScioItJoELBT7g7+cD7nyU7OvpQ1U2fk0xVkCeNvYU0xS1vP4o/VnZRpup7f7Tkiq+2rf4fjwYr3HHnJjwak1l9bsw6FkgzKaVvSdiUJHMVxiIuLd3fVozR7qjBBhTDxSlWGOpSgd+ttpgMZwU5zQjdaVQr1D7E8M0979ZnWMrNRyLiAUeHaPILS815b+ijgqR+i5nmu0/FTCGM9Ik4KIzIfWq8AdfPdbRiq8c+LrrTPfyKcIQJaHmfduYRM4LycGWwzkXFBNtLrJ7uFLG9RDVemOHuHOWIJX8qCUIV4XuESXxH3fUQr6r+yxquTJbzXxNtoaLa6tBOTQWKDrRjT4z9Mf9Im14F2V59EUDoQowHx5bjunOH5wg3ruYNKYYBFRYra5kx0CkKrqFBzyl8fTUEQLyx1HWTVUC1WTXEeD/aFKOSIxW5DxZr5W4LLlW2+Raa52ZzY28Q6AdueFQCRzoJ70/GsJRlSsBdWNOHN4gSp1cZuToLWY15y64QhAMVDpikB+V4hmkbceLiTqeWzTStNL1sa32RHr6i/9zeFZw1pMD1+eOg9x6fgODfh2sqr/zPbu2oONsHnc4D2jwsEax4o+Dv5QHLvK7jdyWUmu47a9QReoexXK60jZXs3CA="

jobs:
   include:
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="manylinux2014" PLATFORM="aarch64"
    - arch: s390x
      env: POLICY="manylinux2014" PLATFORM="s390x"
    - arch: ppc64le
      env: POLICY="manylinux2014" PLATFORM="ppc64le"
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="manylinux_2_28" PLATFORM="aarch64"
    - arch: s390x
      env: POLICY="manylinux_2_28" PLATFORM="s390x"
    - arch: ppc64le
      env: POLICY="manylinux_2_28" PLATFORM="ppc64le"
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="musllinux_1_2" PLATFORM="aarch64"
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="musllinux_1_2" PLATFORM="armv7l"
    - arch: s390x
      env: POLICY="musllinux_1_2" PLATFORM="s390x"
    - arch: ppc64le
      env: POLICY="musllinux_1_2" PLATFORM="ppc64le"

before_install:
  - if [ -d "${HOME}/buildx-cache/.buildx-cache-${POLICY}_${PLATFORM}" ]; then cp -rlf ${HOME}/buildx-cache/.buildx-cache-${POLICY}_${PLATFORM} ./; fi

install:
  - docker version
  - docker buildx version
  - docker buildx create --name builder-manylinux --driver docker-container --use
  - docker buildx inspect --bootstrap --builder builder-manylinux 2>&1 | tee /dev/null

script: |
  BUILD_STATUS=success
  (while true; do echo "travis_wait"; docker stats --no-stream; free; df -h; sleep 30; done) &
  WAIT_PID=$!
  COMMIT_SHA=${TRAVIS_COMMIT} ./build.sh || BUILD_STATUS=failed
  kill -9 ${WAIT_PID}
  if [ "${BUILD_STATUS}" != "success" ]; then
    exit 1
  fi
  if [ -d "${HOME}/buildx-cache" ]; then
    rm -rf ${HOME}/buildx-cache
  fi
  mkdir ${HOME}/buildx-cache
  if [ "${MANYLINUX_BUILD_FRONTEND}" != "docker" ]; then
    cp -rlf ./.buildx-cache-* ${HOME}/buildx-cache/
  fi

deploy:
  provider: script
  dpl_version: 1.10.16
  script: COMMIT_SHA=${TRAVIS_COMMIT} ./deploy.sh
  on:
    branch: main
    repo: pypa/manylinux
