name: Clean image cache

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        type: boolean
        required: false
        default: false
  schedule:
    - cron: "30 10 * * 3"  # At 10:30 on Wednesday.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: false

permissions: {}

jobs:
  cleanup:
    if: github.repository == 'pypa/manylinux'
    name: Clean image cache
    runs-on: ubuntu-latest
    permissions:
      packages: write  # needed to delete images
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          package: manylinux-cache
          delete-untagged: true
          dry-run: ${{ (github.event_name == 'workflow_dispatch') && fromJSON(github.event.inputs.dry-run) }}
